[loadbalancers]
# moet ook via private ip anders werkt ping commando niet door SG-rules : ansible all -i hosts.ini -m ping
rp-public-nginx ansible_host=10.0.2.155 ansible_user=ubuntu

[app_servers]
rp-private-api-media ansible_host=10.0.4.32 ansible_user=ubuntu

[workers]
rp-private-processor ansible_host=10.0.4.20 ansible_user=ubuntu

#[test]
#rp-private-test-2 ansible_host=10.0.3.58 ansible_user=ubuntu

# vergeet niet ssh-key te adden aan ssh-agent in terminal anders werkt het ook niet
# voorbeeld: ssh-add /home/dascha/Downloads/test-ec2-key.pem
[all:vars]
ansible_connection=ssh
ansible_ssh_private_key_file=/home/dascha/Downloads/test-ec2-key.pem
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=ec2-user@52.51.220.70 -o ForwardAgent=yes'
