[loadbalancers]
rp-public-nginx ansible_host=10.0.1.142

[app_servers]
rp-private-api-media ansible_host=10.0.4.8 # 10.0.4.32 is version 3

[workers]
rp-private-processor ansible_host=10.0.4.5 # 10.0.4.20 is version 3

[keycloak]
rp-private-keycloak-ansible ansible_host=10.0.3.225 # 10.0.3.153 is keycloak-docker ec2 instance

[all:vars]
ansible_connection=ssh
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/adam/Documents/test-ec2-key.pem
ansible_python_interpreter=/usr/bin/python3
bastion_user=ec2-user
bastion_host=52.51.220.70
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump={{ bastion_user }}@{{ bastion_host }}'
