---
- import_playbook: deploy_media.yml
- import_playbook: deploy_processor.yml
- import_playbook: deploy_api.yml

- name: Run integration test on API server
  hosts: app_servers
  become: true
  gather_facts: false
  tasks:
    - name: Run integration test
      ansible.builtin.command: npm run test:integration
      args:
        chdir: "{{ app_dir }}/api"
