---
- name: Exercise 02 with playbook
  hosts: all
  become: true

  tasks:

    - name: Copy pyhon file
      ansible.builtin.copy:
        src: hello.py
        dest: /tmp/hello.py
        owner: vagrant
        group: vagrant
        mode: '0644'

    - name: Do a ping
      ansible.builtin.ping:
        data: "Hello from inside"
