---
- name: My playbook
  hosts: all
  tasks:
    - name: Run command and store output in variable
      ansible.builtin.shell: date
      register: date_output

    - name: Display output variable value
      ansible.builtin.debug:
        msg: "{{ date_output.stdout }}"